{
  description = "Axiom System Flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.11";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager/release-25.11";
    kickstart = {
      url = "github:nvim-lua/kickstart.nvim";
      flake = false;
    };
    stylix = {
      url = "github:nix-community/stylix/release-25.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixvim = {
      url = "github:nix-community/nixvim/nixos-25.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    gittype = {
      url = "github:unhappychoice/gittype";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      nixpkgs-unstable,
      home-manager,
      kickstart,
      stylix,
      nixvim,
      gittype,
      ...
    }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

      # Build axiom-rebuild from local source
      axiom-rebuild = pkgs.rustPlatform.buildRustPackage {
        pname = "axiom-rebuild";
        version = "0.1.0";
        src = ./tools/axiom-rebuild;
        cargoLock.lockFile = ./tools/axiom-rebuild/Cargo.lock;
      };

      # Build launcher from local source
      launcher = pkgs.rustPlatform.buildRustPackage {
        pname = "launcher";
        version = "0.1.0";
        src = ./tools/launcher;
        cargoLock.lockFile = ./tools/launcher/Cargo.lock;
      };

      # Install ck from prebuilt binary
      ck-pkg = pkgs.stdenv.mkDerivation rec {
        pname = "ck";
        version = "0.7.0";

        src = pkgs.fetchurl {
          url = "https://github.com/BeaconBay/ck/releases/download/${version}/ck-${version}-x86_64-unknown-linux-gnu.tar.gz";
          sha256 = "sha256-Bmt/PnRIYI4215JhWhfNwajszmXb2LURYhyVlNQ7jPE=";
        };

        sourceRoot = ".";

        nativeBuildInputs = [
          pkgs.autoPatchelfHook
        ];
        buildInputs = [ pkgs.stdenv.cc.cc.lib ];

        installPhase = ''
          mkdir -p "$out/bin"
          install -Dm755 ck "$out/bin/ck"
        '';
      };

      # Build guide packages from local source
      guidePackages = rec {
        guide = pkgs.buildGoModule {
          pname = "guide";
          version = "0.1.0";
          src = ./tools/guide;
          vendorHash = "sha256-asGtQIKm05mQHXU8vRKhcNAFzZh0R0z27aReCcHszeo=";
          subPackages = [ "cmd/guide" ];
          nativeBuildInputs = with pkgs; [ pkg-config ];
          ldflags = [
            "-s"
            "-w"
          ];
        };

        guide-llama-launcher = pkgs.buildGoModule {
          pname = "guide-llama-launcher";
          version = "0.1.0";
          src = ./tools/guide;
          vendorHash = guide.vendorHash;
          subPackages = [ "cmd/guide-llama-launcher" ];
          nativeBuildInputs = with pkgs; [ pkg-config ];
          ldflags = [
            "-s"
            "-w"
          ];
        };
      };

      # Guide overlay
      guideOverlay = final: prev: guidePackages;

      # Guide NixOS module
      guideModule = import ./tools/guide/nixos-module.nix;

      # Import users data generated by axiom-rebuild
      usersData = import ./config/system/users-data.nix;

      # Shared home-manager modules for all users
      # External modules + home.nix + per-user configurable modules from modules/
      sharedHomeModules = [
        stylix.homeModules.stylix
        nixvim.homeModules.nixvim
        ./home.nix
      ] ++ (import ./modules);

      # Helper to create home-manager config for a user
      # Imports per-user config if it exists, otherwise uses empty config
      # Note: sharedHomeModules are applied via home-manager.sharedModules
      mkUserHomeConfig = username: {
        imports = 
          let configPath = ./config/users + "/${username}.nix";
          in if builtins.pathExists configPath then [ configPath ] else [];
      };

      # Generate home-manager.users attrset for all users (curator + others)
      allUsernames = [ "curator" ] ++ usersData.usernames;
      homeManagerUsers = builtins.listToAttrs (
        map (username: {
          name = username;
          value = mkUserHomeConfig username;
        }) allUsernames
      );
    in
    {
      # Export axiom-rebuild package
      packages.${system} = {
        axiom-rebuild = axiom-rebuild;
        default = axiom-rebuild;
      };

      nixosConfigurations.axiom = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          {
            nixpkgs.overlays = [
              guideOverlay
              (final: prev: {
                launcher = launcher;
                axiom-rebuild = axiom-rebuild;
                ck = ck-pkg;
              })
            ];
          }
          ./configuration.nix
          stylix.nixosModules.stylix
          guideModule
          home-manager.nixosModules.home-manager
          {
            # home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup";
            home-manager.extraSpecialArgs = {
              inherit kickstart gittype;
              launcher = launcher;
              pkgs-unstable = import nixpkgs-unstable {
                system = "x86_64-linux";
                config.allowUnfree = true;
              };
            };
            home-manager.sharedModules = sharedHomeModules;
            # Per-user configs are generated by axiom-rebuild from HOCON files
            home-manager.users = homeManagerUsers;
          }
        ];
      };
    };
}
