{
  description = "Axiom System Flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.05";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager/release-25.05";
    kickstart = {
      url = "github:nvim-lua/kickstart.nvim";
      flake = false;
    };
    stylix = {
      url = "github:nix-community/stylix/release-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    guide = {
      url = "git+file:///home/edmund/wonderinstruments/guide";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixvim = {
      url = "github:nix-community/nixvim/nixos-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    parental-controls = {
      url = "git+file:///home/edmund/wonderinstruments/parental-controls";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    launcher = {
      url = "git+file:///home/edmund/wonderinstruments/launcher";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    gittype = {
      url = "github:unhappychoice/gittype";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      nixpkgs-unstable,
      home-manager,
      kickstart,
      stylix,
      guide,
      nixvim,
      parental-controls,
      launcher,
      gittype,
      ...
    }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

      # Build axiom-rebuild from local source
      axiom-rebuild = pkgs.rustPlatform.buildRustPackage {
        pname = "axiom-rebuild";
        version = "0.1.0";
        src = ./tools/axiom-rebuild;
        cargoLock.lockFile = ./tools/axiom-rebuild/Cargo.lock;
      };
    in
    {
      # Export axiom-rebuild package
      packages.${system} = {
        axiom-rebuild = axiom-rebuild;
        default = axiom-rebuild;
      };

      nixosConfigurations.axiom = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          {
            nixpkgs.overlays = [
              guide.overlays.default
              (final: prev: {
                parental-controls = parental-controls.packages.${prev.system}.default;
                launcher = launcher.packages.${prev.system}.default;
                axiom-rebuild = axiom-rebuild;
              })
            ];
          }
          ./configuration.nix
          stylix.nixosModules.stylix
          guide.nixosModules.default
          home-manager.nixosModules.home-manager
          {
            # home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup";
            home-manager.extraSpecialArgs = {
              inherit kickstart launcher gittype;
              pkgs-unstable = import nixpkgs-unstable {
                system = "x86_64-linux";
                config.allowUnfree = true;
              };
            };
            home-manager.sharedModules = [
              stylix.homeModules.stylix
              nixvim.homeModules.nixvim
              ./home.nix
              ./modules/stylix.nix
              ./modules/neovim.nix
              ./modules/web.nix
              ./modules/rofi.nix
              ./modules/applications.nix
              ./modules/keybindings.nix
              ./modules/docs.nix
              ./modules/python-scripts.nix
              ./modules/bashcrawl.nix
              ./modules/fish.nix
              ./modules/i3.nix
              ./modules/polybar.nix
              ./modules/picom.nix
              ./modules/kitty.nix
              ./modules/screensaver.nix
              ./modules/fractal-wallpaper.nix
              ./modules/sounds.nix
              ./modules/clipboard-monitor.nix
              ./modules/micro.nix
              ./modules/thonny.nix
              ./modules/custom-icons.nix
              ./modules/system-commands.nix
              ./modules/tmux.nix
              ./modules/launcher.nix
              ./modules/file-commands.nix
              ./modules/xplr.nix
              ./modules/navi.nix
              ./modules/musopen.nix
              ./modules/gittype.nix
              ./modules/axiom-config.nix
            ];
            # Per-user configs are generated by axiom-rebuild from HOCON files
            home-manager.users.edmund = {
              imports = [ ./config/users/edmund.nix ];
            };
          }
        ];
      };
    };
}
