# Auto-generated by axiom-rebuild for user: curator
# Do not edit this file directly - edit ~/config/axiom/config.conf instead

{ ... }:
{
  # Default curator config - customize via ~/config/axiom/config.conf
}
