# Axiom Users Module
#
# Manages system users based on generated data from /etc/axiom/users.conf.
# The curator (owner) is always created with root permissions.
# Additional users are defined in users-data.nix generated by axiom-rebuild.

{ config, lib, pkgs, ... }:

let
  # Import the generated user data
  usersData = import ../config/system/users-data.nix;

  # Default curator password hash for "wonderinstruments"
  # Change via /etc/axiom/users.conf: curator { hashedPassword = "..." }
  defaultCuratorPasswordHash = "$6$f77OM3cDVk1VHC2j$f4wIJTon.ERhQcOdvm8DpIdZiK7FzAhEQc5MZb1Zf7NRv1fvum6FzOySO4HCDkM9c9D74a75h53EGZ2xY.Txf1";

  # Helper to create a NixOS user definition
  mkUser = username: userData: {
    isNormalUser = true;
    description = userData.displayName or username;
    extraGroups = [ "networkmanager" ]
      ++ lib.optionals (userData.hasRootPermissions or false) [ "wheel" ];
    hashedPassword = userData.hashedPassword or "";
  };

  # Create user definitions for all users from the data file
  generatedUsers = lib.mapAttrs mkUser usersData.users;

  # Get curator config from users-data.nix if present
  curatorConfig = usersData.curator or {};

  # The curator is always created with root permissions
  curatorUser = {
    curator = {
      isNormalUser = true;
      description = curatorConfig.displayName or "Curator";
      extraGroups = [ "wheel" "networkmanager" ];
      # Use configured password or fall back to default
      hashedPassword = curatorConfig.hashedPassword or defaultCuratorPasswordHash;
    };
  };

  # Merge curator with generated users
  allUsers = curatorUser // generatedUsers;

in
{
  config = {
    # Declarative user management - users not defined here will be removed
    users.mutableUsers = false;

    # All users including curator
    users.users = allUsers;

    # Allow all users to run axiom-rebuild without password
    # (axiom-rebuild itself restricts non-wheel users to their own config)
    security.sudo.extraRules = [
      {
        groups = [ "users" ];
        commands = [
          {
            command = "${pkgs.axiom-rebuild}/bin/axiom-rebuild";
            options = [ "NOPASSWD" ];
          }
        ];
      }
    ];
  };
}
