# Auto-generated by axiom-rebuild from /etc/axiom/system.conf
# Do not edit this file directly - edit /etc/axiom/system.conf instead

{
  hostname = "axiom";
  timezone = "America/Los_Angeles";
  locale = "en_US.UTF-8";
}
