# Auto-generated by axiom-rebuild from /etc/axiom/users.conf
# Do not edit this file directly - edit /etc/axiom/users.conf instead

{
  # Curator config (optional overrides)
  curator = {};

  # List of usernames (excluding curator)
  usernames = [];

  # User details keyed by username
  users = {};
}
