// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateSudo(arg1) {
  return window['go']['main']['App']['AuthenticateSudo'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadNixConfig() {
  return window['go']['main']['App']['ReadNixConfig']();
}

export function SaveNixConfig(arg1) {
  return window['go']['main']['App']['SaveNixConfig'](arg1);
}
