// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateSudo(arg1:string):Promise<void>;

export function IsAuthenticated():Promise<boolean>;

export function Quit():Promise<void>;

export function ReadNixConfig():Promise<Record<string, any>>;

export function SaveNixConfig(arg1:Record<string, any>):Promise<void>;
